name: Rust

on:
  push:
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code
        run:  >
          cargo check
          # --verbose
      - name: Publish
        run: >
          cargo publish
          --locked
          --token ${{ secrets.CRATES_TOKEN }}
          --verbose
